title: Your awesome title
description: >
  Description

logo: https://media-exp1.licdn.com/dms/image/C4E0BAQEk6j16N3wROA/company-logo_200_200/0/1519885446512?e=1656547200&v=beta&t=bT_ccGhQ1yRtvqP_-tbkmGWpbu6FGmVDOTjMXbfD1PE

minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    twitter: jekyllrb
    github: jekyll
    linkedin: samsara-web-services-ltd.
theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
